### ISSUE TITLE
Please help?

### ISSUE THREAD

**Issue by MachineSaver** [megoRU/wg-easy-wrapper#1]
I am not a Java guy, what you've written looks very professional but alas I cannot make heads or tails of how you do it.

If I send a POST request to a running instance of wg-easy what do I need to include to generate a new session?

Can I use the webgui password? Do I need to generate some new password? Do I need to change settings in my dockercompose file to expose the API when not logged in?

Thanks in advance!

**Comment by megoRU** [comment]
If I understood correctly, you are connecting by IP

You can declare a variable in a separate class in the . public static final field. And already interact with WG-EASY through this instance. I also want to clarify that it is better to check the session. She may log out after some time.
When you create an instance, it is already a session. You can work with it until it runs out. You can update it by `setSession();`

```Java
public class WgEasyStorage {

public static final WgEasyAPI api = new WgEasyAPI.Builder()
            .password("password")
            .ip("xxx.xxx.xxx.xxx")
            .port(51821)
            .build();
}
```

Wrap this code in an endless stream. 
[www.codejava.net](https://www.codejava.net/java-core/concurrency/java-concurrency-scheduling-tasks-to-execute-after-a-given-delay-or-periodically)
```Java
if (WgEasyStorage.api != null) {
   Session session = WgEasyStorage.api.getSession();
       if (session != null) {
          boolean authenticated = session.isAuthenticated();
          if (!authenticated) {
             WgEasyStorage.api.setSession();
         }
    }
}
```

**Comment by MachineSaver** [comment]
I am trying to talk to the API of wg-easy from my home computer over the internet to the server that is running on a cloud platform. I am pointing my domain at the IP address of the server running WG-easy.
http://my-domain.com:51821
This, of course, resolves to an IP address.

So if I did a simple curl request would it look like this?

```
curl -X POST \
     -H "Content-Type: application/json" \
     -d '{"password":"WebGUI_Password_for_WG-Easy"}' \
     http://my-domain.com:51821
```

Does this make sense?

**Comment by megoRU** [comment]
http://my-domain.com:51821/api/session

**Comment by MachineSaver** [comment]
Dude you are my hero. Thanks for this, now I can interact with the instance from a script running on the computer I'm installing the vpn on instead of manually generating from the UI. Much appreciated!

**Comment by megoRU** [comment]
nice to hear
